site_name: CKAN Documentation
site_url: https://ckan-documentation.front-matter.io
repo_url: https://github.com/front-matter/ckan-documentation
edit_uri: blob/main/docs/

theme:
  name: material
  features:
    - content.code.copy

  markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
